-- V40__common_migrations_start_here.sql
--
-- LA PRIMERA MIGRACIÓN DE db/common, Y LA QUE HACE QUE LA CARPETA NO SEA MUDA.
--
-- POR QUÉ EXISTE
-- db/common se agregó a los locations de los tres perfiles para que las migraciones nuevas se
-- escriban una sola vez en vez de dos. Pero una carpeta declarada y VACÍA no prueba nada:
-- Flyway aplica lo que encuentra y reporta éxito, así que arrancar con la carpeta en los
-- locations y sin ningún .sql adentro se ve idéntico a tenerla mal escrita o a no tenerla.
--
-- Eso se midió: con la carpeta vacía, un arranque del perfil prod contra una base recreada
-- reportó "Successfully applied 32 migrations ... now at version v32". Treinta y dos son las de
-- db/migration. La carpeta nueva no aportó nada y nadie se enteró.
--
-- Con este archivo, ese mismo arranque tiene que decir 33 y quedar en v40. Es la diferencia
-- entre "la carpeta está declarada" y "la carpeta funciona", y es verificable de un vistazo en
-- el log de arranque, sin herramientas.
--
-- QUÉ HACE
-- Deja una fila que registra la convención vigente. No es decorativa: es la única evidencia
-- consultable, EN LA BASE DE PRODUCCIÓN, de que el mecanismo de db/common está andando. Un
-- SELECT sobre esta tabla responde "¿las migraciones nuevas llegan?" sin leer configuración ni
-- revisar logs.
--
-- ES TAMBIÉN EL EJEMPLO TRABAJADO DE LAS REGLAS DE PORTABILIDAD
-- Usa a propósito las dos formas que db/common/README.md manda usar y que reemplazan a las dos
-- que más aparecen en el código viejo:
--
--   GENERATED BY DEFAULT AS IDENTITY   en vez de BIGSERIAL, que es de PostgreSQL y que H2 solo
--                                      acepta por emulación de MODE=PostgreSQL
--   CURRENT_TIMESTAMP                  en vez de NOW(), que también es de PostgreSQL
--
-- Si alguna de las dos dejara de funcionar en alguno de los motores, se rompe acá y no en la
-- primera migración que importe.
--
-- SI MAÑANA HAY UNA MIGRACIÓN DE VERDAD
-- Esta se queda igual. Pasa a ser el registro de cuándo empezó la convención, que es
-- información que no está en ningún otro lado una vez que el historial de git se hace largo.

CREATE TABLE schema_conventions (
    schema_convention_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(80)  NOT NULL,
    description          VARCHAR(400) NOT NULL,
    adopted_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ux_schema_conventions_name UNIQUE (name)
);

INSERT INTO schema_conventions (name, description)
VALUES (
    'common-migrations',
    'Las migraciones nuevas van en db/common, numeradas desde V40, escritas una sola vez para PostgreSQL y H2. db/migration y db/migration-h2 quedan congeladas como el esquema historico. Ver db/common/README.md.'
);
